export const APP_VERSION = 'TFFRv19';

export enum UserRole {
  GUEST = 'GUEST',
  FAN = 'FAN',
  ADMIN = 'ADMIN'
}

export enum Screen {
  LOGIN = 'LOGIN',
  ADMIN_PERSONNEL_SELECT = 'ADMIN_PERSONNEL_SELECT',
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  ONBOARDING = 'ONBOARDING',
  LOGIN_FLOW = 'LOGIN_FLOW',
  RECOVER_PASSWORD = 'RECOVER_PASSWORD',
  SELECT_SPECIALTY = 'SELECT_SPECIALTY',
  FEED = 'FEED',
  MARKET = 'MARKET',
  WALLET = 'WALLET',
  ADMIN_TEAM_CHAT = 'ADMIN_TEAM_CHAT',
  ADMIN_DASH = 'ADMIN_DASH',
  
  // INDIVIDUAL DASHBOARDS (CLONES)
  DASH_GOD_MODE = 'DASH_GOD_MODE',
  DASH_ARCHY = 'DASH_ARCHY',
  DASH_SPONSOR = 'DASH_SPONSOR',
  DASH_OWNER = 'DASH_OWNER',
  DASH_MANAGER = 'DASH_MANAGER',
  DASH_PROMOTER = 'DASH_PROMOTER',
  DASH_ASSISTANT = 'DASH_ASSISTANT',
  DASH_MODERATOR = 'DASH_MODERATOR',
  
  // THE 8 AGENTS
  DASH_DATIN = 'DASH_DATIN',
  DASH_SIRENA = 'DASH_SIRENA',
  DASH_VIPY = 'DASH_VIPY',
  DASH_GUIDE = 'DASH_GUIDE', // Also AI_SUPPORT
  DASH_ASSI = 'DASH_ASSI',
  DASH_DESY = 'DASH_DESY',
  DASH_MARK = 'DASH_MARK',
  DASH_HACKY = 'DASH_HACKY',
  DASH_FLOR = 'DASH_FLOR'
}