import { Message, MessageType, User } from '../../types';

export const CURRENT_USER: User = { id: 'me', username: 'NeoDrifter', meritScore: 245, avatarUrl: 'https://picsum.photos/200/200', isVerified: true };
export const SYSTEM_ALERTS = [ "⚠️ NETWORK FLUX DETECTED. SWITCHING TO LIQUID MODE.", "🏆 SOCIAL LOTTERY: 2 Front Row Tickets! Comment to win!", "💰 New High-Value Gig Available: Line Holding at Gate B." ];
export const MOCK_USERS: User[] = [
  { id: 'u3', username: 'CyberPunk99', meritScore: 50, avatarUrl: 'https://picsum.photos/203/203' },
  { id: 'u4', username: 'VenueStaff_Sarah', meritScore: 300, avatarUrl: 'https://picsum.photos/204/204', isVerified: true },
  { id: 'u5', username: 'CryptoKing', meritScore: 120, avatarUrl: 'https://picsum.photos/205/205' },
  { id: 'u1', username: 'TrafficWatcher', meritScore: 180, avatarUrl: 'https://picsum.photos/201/201', isVerified: true },
  { id: 'u2', username: 'FastValet', meritScore: 290, avatarUrl: 'https://picsum.photos/202/202', isVerified: true },
];
export const INITIAL_MESSAGES: Message[] = [
  { id: 'msg-1', text: 'Welcome to TheFunFanReporter Hub. Connectivity is currently stable. Merit Score sync active.', sender: 'SYSTEM', timestamp: new Date(Date.now() - 1000 * 60 * 5), type: MessageType.SYSTEM },
  { id: 'msg-2', text: 'Road 101 is closed due to VIP motorcade! Avoid the north entrance.', sender: MOCK_USERS[3], timestamp: new Date(Date.now() - 1000 * 60 * 4), type: MessageType.ALERT, metadata: { location: 'North Gate', amount: 5 } },
  { id: 'msg-3', text: 'I can offer Valet Parking services. I have a secure spot 2 blocks away.', sender: MOCK_USERS[4], timestamp: new Date(Date.now() - 1000 * 60 * 2), type: MessageType.GIG_OFFER, metadata: { gigTitle: 'Valet Parking', amount: 100 } }
];
export const TOPICS = [ { name: "NORTH GATE", keywords: ["gate", "north", "blocked", "line", "entry"] }, { name: "SOUND SYSTEM", keywords: ["sound", "bass", "cant hear", "loud", "mic"] }, { name: "SURPRISE GUEST", keywords: ["guest", "who is it", "stage", "omg", "look"] } ];
export const SPAM_PHRASES = [ "OPEN THE DOORS!", "QR CODE NOT WORKING", "WE WANT WATER", "LFG!!!!" ];
export const UNIQUE_MESSAGES = [ "Anyone know if the merch stand at Section 100 still has jerseys?", "Traffic outside is crazy, stick to the shuttle.", "Just won 5 coins for reporting the broken tap!", "The halftime show prep looks insane from here.", "Need a charger, offering 10 MC for 15 mins!", "Who's going to the afterparty at The District?", "Security is taking water bottles at Gate C, heads up.", "Found a set of keys near the pretzel stand. Turned them in.", "Is the VIP lounge open to Merit Score 300+ yet?", "My network keeps dropping, anyone else?", "This bass is literally shaking my nachos.", "Looking for 2 people to share a ride back to downtown.", "The line for the ladies' room is shorter on the 2nd floor.", "Just saw the lead singer warming up backstage!", "Selling a fast pass for the photo booth, 20 MC.", "Does anyone have a spare poncho? It looks like rain.", "Pizza slice prices are actually decent today.", "Can someone explain the rules for the Social Lottery?", "I think I just spotted a celebrity in the box seats.", "My Merit Score just went up for helping that lost kid.", "Charging station A is full, try station B near the exit.", "The visual effects on the main screen are mind-blowing.", "Leaving early, have a parking pass if anyone needs it.", "Don't forget to hydrate, it's getting hot in the pit.", "Is there an ATM that actually works near Section 200?", "The acoustics in the upper deck are surprisingly good.", "Anyone want to trade a size L shirt for an XL?", "The drummer is absolutely killing it right now.", "Crowd control is doing a great job moving people out.", "Where is the best spot for a group photo?", "Lost my sunglasses, aviators, reward 15 MC.", "The specialized cocktails at the Blue Bar are sold out.", "Check your pockets, pickpockets reported in the mosh pit.", "WiFi password for the guest network changed to 'LIVE2025'.", "Can we get a wave going in the south stands?", "The pyrotechnics setup looks dangerous but cool.", "My ears are ringing, anyone have spare plugs?", "That guitar solo was longer than my last relationship.", "Gate A is strictly for staff now, go to Gate D.", "Just got a notification for a flash gig cleaning confetti.", "The projection mapping on the ceiling is trippy.", "Anyone else stuck in the elevator at the west tower?", "Best vegan food is at the green truck outside.", "They just announced a surprise encore!", "My phone is at 4%, going dark soon.", "The energy in here is absolutely electric tonight." ];